# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_ID', models.IntegerField()),
                ('Comment_User_name', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=255)),
                ('Createtime', models.DateTimeField(auto_now=True)),
                ('IsMap', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GMap',
            fields=[
                ('Map_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=255)),
                ('User_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=32)),
                ('Password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=32)),
                ('Map_ID', models.BigIntegerField()),
                ('Like', models.IntegerField(default=0)),
                ('Read', models.IntegerField(default=0)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('Description', models.CharField(max_length=64, null=True)),
                ('State_name', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
